- hosts: "{{ build_hosts | default('vagrant') }}"
  tasks:
  - name: Set up timezone
    become: true
    timezone:
      name: Asia/Tokyo    # JST

- name: Set up singularity
  hosts: "{{ build_hosts | default('vagrant') }}"
  roles:
  - name: Install vim
    role: vim
  - name: Install golang
    role: golang
    vars:
      golang_version: "1.17.2"
  - name: Install singularity
    role: singularity
