- name: Set up
  hosts: "{{ build_hosts | default('vagrant') }}"
  roles:
  - name: set up locales
    role: common/locale
    vars:
      locale_timezone: "Asia/Tokyo"  # JST
  - name: Install vim
    role: vim
  - name: Install golang
    role: golang
    vars:
      golang_version: "1.17.2"
  - name: Install singularity
    role: singularity
