- name: set up
  hosts: "{{ build_hosts | default('vagrant') }}"

  # tasks:
  # - name: add the user for provisioning
  #   become: true
  #   ansible.builtin.user:
  #     name: "{{ provision_user }}"
  #     groups: sudo
  roles:
  - name: Install golang
    role: golang
    vars:
      golang_version: "1.17.2"
  - name: Install singularity
    role: singularity
