- name: Set up common
  hosts: "{{ build_hosts | default('vagrant') }}"
  roles:
  - name: Install vim
    role: vim
  - name: Install golang
    role: golang
    vars:
      golang_version: "1.17.2"
  - name: Install singularity
    role: singularity
